### ISSUE TITLE
Callback not working

### ISSUE THREAD

**Issue by avallebarco** [gabornemeth/StravaSharp#11]
I cloned the project and I changed the ClientId and the ClientSecret.

I run the project and I log-in page strava, then the callback funtion throw an error. I attach a image of the error.
It`s a bug? or have I done something wrong?

could you help me?
thanks

![errorstrava](https://user-images.githubusercontent.com/25487186/52431546-b94bdc00-2b08-11e9-85a1-605160ca6073.JPG)

**Comment by the-coding-panda** [comment]
Hello,

I was having this issue when implementing it with .Net Core.

Looks like Gabor fixed this in the latest version, updating to version 0.5.5 solved this for me 👍

**Comment by gabor-nemeth** [comment]
@avallebarco do you still have the issue using version 0.5.5?

**Comment by avallebarco** [comment]
I solved my issue upgrading to version 0.5.5
Thanks.
