### ISSUE TITLE
Upload activity_id is long

### ISSUE THREAD

**Issue by chrisfoulds** [gabornemeth/StravaSharp#15]
https://developers.strava.com/docs/reference/#api-models-Upload

Upload activity_id is long

You have it set to a int which causes exceptions on the parsing of the data

[JsonProperty("id")]
        public long Id { get; }
        [JsonProperty("external_id")]
        public string ExternalId { get; }
        [JsonProperty("activity_id", NullValueHandling = NullValueHandling.Ignore)]
        public int ActivityId { get; }
        [JsonProperty("status")]
        public string Status { get; }
        [JsonProperty("error")]
        public string Error { get; }
        [JsonIgnore]
        public bool IsReady { get; }

**Comment by chrisfoulds** [comment]
https://github.com/gabornemeth/StravaSharp/blob/d591c749ab93012056de0a2e1f1268f486d11aca/src/StravaSharp/UploadStatus.cs

**Comment by gabornemeth** [comment]
@rjvdboon thank you for the fix.
