### ISSUE TITLE
Interfaced implementation?

### ISSUE THREAD

**Issue by OracPrime** [gabornemeth/StravaSharp#17]
I'm just about to rework a Strava mash-up app that I've done a few versions of, but it's time for a new one (the previous is broken in various ways).  My prior experience of developing an app with Strava is that particular during the test and debug phase, it's easy to hit Strava's rate limits.  For this reason, and for various other issues of testability, I can't help feeling that this app would be a better match for my needs if it had an interface-based external definition.  This could then be mocked for testing and development either for producing reproducible tests or to avoid rate limits.

Is this something you have considered?  Is it something that you would be interested in help with?

**Comment by OracPrime** [comment]
To further underline my point - the test project fails if run as cloned.

**Comment by gabornemeth** [comment]
It totally makes sense, although we still won't get notified through the tests if some change in the Strava API breaks the code in production. And we have to update our mocked version to those changes as well.
Feel free to implement it and let me know if you have some preliminary results or you can submit a PR as well.

**Comment by OracPrime** [comment]
Of course this will be a breaking change for any existing users, as I'll be making the concrete classes (e.g. SegmentEffort) internal, and an ISegmentEffort public.

I'd also propose renaming StravaClient to StravaAuthClient and Client to StravaClient, as they match watch is going on more closely (although of course the latter one will be IStravaClient.  Still thinking about whether publishing the concrete StravaAuthClient is needed/desired

**Comment by OracPrime** [comment]
I've made some good progress on this, but because it's a breaking change I don't want to issue a PR until I've got something complete.  However I'm about to go on holiday for a couple of weeks so there will be a pause.  In the meantime I've opened a ticket with Strava to request an api to give a temporary access token for a test athlete so that we can auto-test the api out of the box.

**Comment by gabornemeth** [comment]
I would only mock the service of Strava API, but not the POCOs. I'm still concerned about maintaining a service mimicking Strava API, because we have to constantly watch for changes and adjust it. I have a test user with activities, etc., but i did not publish the token for it - that's why tests fail for anyone else.

**Comment by OracPrime** [comment]
The approach I'm taking is to set up an azure function which will support an api that returns a temporary access token for the test app, keeping the client secret secret.

Although I am also talking to Strava support about this.

I'm back at the keyboard on the 28th.

Regards

David 

On 17 May 2019 20:38:19 BST, "Németh Gábor" <notifications@github.com> wrote:
>I would only mock the service of Strava API, but not the POCOs. I'm
>still concerned about maintaining a service mimicking Strava API,
>because we have to constantly watch for changes and adjust it. I have a
>test user with activities, etc., but i did not publish the token for it
>- that's why tests fail for anyone else.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/gabornemeth/StravaSharp/issues/17#issuecomment-493574789

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by OracPrime** [comment]
Strava support were unable to offer a better test alternative, so there is now a web function at https://stravaapitest.azurewebsites.net/api/GetToken which will return an access token to authenticate as Mr Test Athlete (https://www.strava.com/athletes/42170685).  This allows unit tests to test against the live server.  So for example

```
        private readonly static HttpClient httpClient = new HttpClient();
        private async Task<string> GetAccessToken()
        {
            var response= await httpClient.GetAsync("https://stravaapitest.azurewebsites.net/api/GetToken");
            string token= await response.Content.ReadAsStringAsync();
            return token;
        }

        private  IAuthenticator StravaTestAthleteAuthenticator;
        private IStravaClient StravaTestAthleteClient;
        private const long cAthleteId = 42170685;
        [OneTimeSetUp]
        public async Task Setup()
        {
            StravaTestAthleteAuthenticator = new TestAuthenticator(await GetAccessToken());
            StravaTestAthleteClient = new StravaClient(StravaTestAthleteAuthenticator);
        }

        [Test]
        public async Task CheckTestAthleteData()
        {
            IAthlete current =await StravaTestAthleteClient.Athletes.GetCurrent();
            Assert.AreEqual("Test", current.FirstName);
            Assert.AreEqual("Athlete", current.LastName);
            Assert.AreEqual(cAthleteId, current.Id);
            Assert.AreEqual("Cambridge", current.City);
        }
```
will work for anyone.  We need to extend the test data for this (I'll clone across some of my own activities so that we get some segment data etc).  And also I intend to add a FakeStrava implementation to the project.  This way we can test our API against live Strava, and our users can test their functionality against a fake strava that won't hit their usage limits (or have network delays).

Still too early for a Pull Request, but feel free to browse my branch and provide constructive feedback.

**Comment by OracPrime** [comment]
> 
> 
> I would only mock the service of Strava API, but not the POCOs. I'm still concerned about maintaining a service mimicking Strava API, because we have to constantly watch for changes and adjust it. I have a test user with activities, etc., but i did not publish the token for it - that's why tests fail for anyone else.

So I've got my implementation returning interfaces everywhere.  But I'm actually thinking that it would be useful to the end user to publish the POCOs (which makes me doubt the value of the interfaces) - as anyone who is for example caching the POCOs locally in (say) Mongo will need a concrete class for Mongo to play with.   Hmmm.

**Comment by rjvdboon** [comment]
to add my own $.02 as a current user of StravaSharp I'd like the POCOs to remain POCOs, they are just dataholders after all. Having the Clients as interfaces does make sense to me.

Oh, I see in your fork that you removed the interfaces for the POCOs already. Then lets just say: thanks for working on this!

**Comment by gabornemeth** [comment]
Closing this according to #20 
Test runs should be fine now on Azure DevOps. Access token is getting refreshed by the test authenticator with the credentials provided as secrets in the pipeline.
