### ISSUE TITLE
How do I get started with StravaSharp?

### ISSUE THREAD

**Issue by HillMountain** [gabornemeth/StravaSharp#2]
Hi,

is there some step-by-step guide on how-to get started?

**Comment by gabornemeth** [comment]
Not yet. There is a sample web app in the repository, which you can examine.

**Comment by gabornemeth** [comment]
I have created a [simple guide](https://github.com/gabornemeth/StravaSharp/blob/master/GettingStarted.md).
Please let me know about what else do you need to make it working. I'm going to extend the guide.
