### ISSUE TITLE
CI test is failing - but I can't see the result

### ISSUE THREAD

**Issue by OracPrime** [gabornemeth/StravaSharp#21]
I've just made a PR.  The CI checks have had some interaction with BitRise.io which has failed.  Attempting to follow the link regarding the failure gives me a 404.

WTF?

(At the time of the PR I did not have a bitrise account; I do now (although I'm nervous about it's write permission to all of my github repos)

**Comment by gabornemeth** [comment]
Moved the CI build to Azure DevOps, everyone should be able to see the results clicking on the badge anonymously too.
