### ISSUE TITLE
Error on client.Activities.GetAthleteActivities

### ISSUE THREAD

**Issue by rollasoc** [gabornemeth/StravaSharp#23]
Same issue as:-
https://github.com/gabornemeth/StravaSharp/issues/3

but with these activity types.

"Error converting value \"VirtualRun\" to type 'StravaSharp.ActivityType'. 
"Error converting value \"Golf\" to type 'StravaSharp.ActivityType'.
"Error converting value \"Handcycle\" to type 'StravaSharp.ActivityType'.
"Error converting value \"Soccer\" to type 'StravaSharp.ActivityType'.

All activities done between June 2019 and July 2019. So none of them are old.

So can't read 38 user's data (out of just over 16000 athletes).

**Comment by OracPrime** [comment]
There are also sailing, skateboard, velomobile and wheelchair.
PR incoming...

**Comment by OracPrime** [comment]
PR24 fixes this... awaiting attention from the powers that be to get it published

**Comment by rjvdboon** [comment]
PR #24 is merged, this can be closed I guess?
